"use client";

import Head from "next/head";
import LayoutFooter from "./LayoutFooter";
import LayoutHeader from "./LayoutHeader";

export default function AppLayout(props) {
  return (
    <>
      <Head>
        <title>Fashion Odyssey</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" sizes="16x16" />
      </Head>
      <div className="px-10 min-h-screen flex flex-col">
        <LayoutHeader />
        <div>{props.children}</div>
      </div>
      <LayoutFooter />
    </>
  );
}
