"use client";

import Head from "next/head";
import LayoutFooter from "./LayoutFooter";
import LayoutHeader from "./LayoutHeader";

export default function AppLayout(props) {
  return (
    <>
      <Head>
        <title>Fashion Odyssey</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" sizes="16x16" />
        <meta property="og:title" content="Fashion Odyssey" />
        <meta
          property="og:description"
          content="Fashion Odyssey에서 최신 패션 트렌드를 알아보세요!"
        />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://fashionodyssey.netlify.app/" />
        <meta
          property="og:image"
          content="https://fashionodyssey.netlify.app/images/og.webp"
        />
      </Head>
      <div className="px-10 min-h-screen flex flex-col">
        <LayoutHeader />
        <div>{props.children}</div>
      </div>
      <LayoutFooter />
    </>
  );
}
